Importação e visualização inicial do extrato bancário

In [ ]:
import pandas as pd
from pathlib import Path

BASE_DIR = Path.cwd().parent
DATA_DIR = BASE_DIR / "data"
RAW_FILE = DATA_DIR / "raw/Bradesco_29042026_080947.CSV"

df = pd.read_csv(
    RAW_FILE,
    sep=';',
    skiprows=2,
    encoding='latin1'
)

df

,Data,Lançamento,Dcto.,Crédito (R$),Débito (R$),Saldo (R$)
0,27/04/2026,SALDO ANTERIOR,NaN,NaN,NaN,"99.073,98"
1,28/04/2026,DEP CORBAN DINHEIRO,711128,"1.000,00",NaN,"100.073,98"
2,28/04/2026,DEP CORBAN DINHEIRO,711128,"1.000,00",NaN,"101.073,98"
3,28/04/2026,STONE MASTER DEBITO STONE INSTITUICAO DE PAGAM...,9235509,"387,09",NaN,"101.461,07"
4,28/04/2026,STONE ELO DEBITO STONE INSTITUICAO DE PAGAMENTO,9235509,"27,57",NaN,"101.488,64"
5,28/04/2026,TRANSFERENCIA PIX REM: JOAO ANDRADE DE LIMA 2...,705324,"88,00",NaN,"101.576,64"
6,28/04/2026,TRANSFERENCIA PIX REM: RENATO CORDEIRO DE SO 2...,758232,"272,00",NaN,"101.848,64"
7,28/04/2026,TRANSFERENCIA PIX REM: Francisco Antonio Per 2...,900058,"90,00",NaN,"101.938,64"
8,28/04/2026,TRANSFERENCIA PIX REM: José Ricardo Lima Roc 2...,906209,"56,00",NaN,"101.994,64"
9,28/04/2026,TRANSFERENCIA PIX REM: ALCIDES NETO QUEIROZ 2...,906476,"28,00",NaN,"102.022,64"
10,28/04/2026,TRANSFERENCIA PIX REM: Michael Duarte de Que 2...,1005501,"1.200,00",NaN,"103.222,64"
11,28/04/2026,TRANSFERENCIA PIX REM: MIGUEL RODRIGUES GURG 2...,1256370,"74,00",NaN,"103.296,64"
12,28/04/2026,TRANSFERENCIA PIX REM: CARCARA CONSTRUCOES E 2...,1404132,"62,00",NaN,"103.358,64"
13,28/04/2026,TRANSFERENCIA PIX REM: Evando da Silva Assun 2...,1503063,"266,00",NaN,"103.624,64"
14,28/04/2026,TRANSFERENCIA PIX REM: SYLVANA A SANTANA 2...,1615383,"170,00",NaN,"103.794,64"
15,28/04/2026,RENTAB.INVEST FACILCRED*,1745769,"0,44",NaN,"103.795,08"
16,28/04/2026,TARIFA REGISTRO COBRANCA QUANDO DO REGISTRO ...,9041633,NaN,"-1,99","103.793,09"
17,28/04/2026,PAGTO ELETRONICO TRIBUTO INTERNET --SEFAZ/CE,5690252,NaN,"-5.449,56","98.343,53"
18,28/04/2026,TRANSFERENCIA PIX DES: M J DINIZ & CIA LTDA 2...,1128026,NaN,"-1.500,00","96.843,53"
19,28/04/2026,TRANSFERENCIA PIX DES: S V COMERCIO DE MATER 2...,1141441,NaN,"-3.218,73","93.624,80"
20,28/04/2026,PIX QR CODE DINAMICO DES: SODINE SOCIEDADE DIS...,1511329,NaN,"-1.382,25","92.242,55"
21,29/04/2026,STONE MASTER CREDITO STONE INSTITUICAO DE PAGA...,402529,"529,25",NaN,"92.771,80"
22,29/04/2026,STONE ELO CREDITO STONE INSTITUICAO DE PAGAMENTO,402529,"516,31",NaN,"93.288,11"
23,29/04/2026,STONE MASTER DEBITO STONE INSTITUICAO DE PAGAM...,402529,"87,12",NaN,"93.375,23"
24,29/04/2026,STONE ELO DEBITO STONE INSTITUICAO DE PAGAMENTO,402529,"93,53",NaN,"93.468,76"
25,Total,NaN,NaN,"5.947,31","-11.552,53","93.468,76"
26,NaN,Lançamentos Futuros,NaN,NaN,NaN,NaN
27,Data,Lançamento,Dcto.,Crédito (R$),Débito (R$),NaN
28,30/04/2026,STONE VISA CREDITO STONE INSTITUICAO DE PAGAMENTO,159330,"169,89",NaN,NaN
29,30/04/2026,STONE MASTER CREDITO STONE INSTITUICAO DE PAGA...,159330,"353,52",NaN,NaN
30,Total do dia,NaN,NaN,"523,41","0,00",NaN
31,04/05/2026,CARTAO CREDITO ANUIDADE,4740110,NaN,"-22,00",NaN
32,Total do dia,NaN,NaN,"0,00","-22,00",NaN
33,11/05/2026,PAGTO ELETRON COBRANCA BRADESCO SEGUROS - SEG...,2425,NaN,"-916,71",NaN
34,11/05/2026,PAGTO ELETRON COBRANCA 070187494301050701BRAD...,3019,NaN,"-1.274,82",NaN
35,11/05/2026,PAGTO ELETRON COBRANCA 070187494001050902BRAD...,3020,NaN,"-582,42",NaN
36,11/05/2026,PAGTO ELETRON COBRANCA 070187493701050900BRAD...,3021,NaN,"-1.274,82",NaN
37,11/05/2026,PAGTO ELETRON COBRANCA 070187493901050902BRAD...,3022,NaN,"-1.274,82",NaN
38,11/05/2026,PAGTO ELETRON COBRANCA 070187494201050902BRAD...,3023,NaN,"-1.274,82",NaN
39,11/05/2026,PAGTO ELETRON COBRANCA 070187494401050900BRAD...,3024,NaN,"-1.274,82",NaN
40,11/05/2026,PAGTO ELETRON COBRANCA 070187493801050701BRAD...,3025,NaN,"-1.274,82",NaN
41,11/05/2026,PAGTO ELETRON COBRANCA 070187494101050902BRAD...,3026,NaN,"-1.274,82",NaN
42,Total do dia,NaN,NaN,"0,00","-10.422,87",NaN
43,NaN,Saldos Invest Fácil / Plus,NaN,NaN,NaN,NaN
44,Data,Histórico,Valor (R$),NaN,NaN,NaN
45,27/04/2026,SALDO INVEST FÁCIL,"99.077,40",NaN,NaN,NaN
46,28/04/2026,SALDO INVEST FÁCIL,"92.246,15",NaN,NaN,NaN

Vou fazer uma pré limpeza, só pra exibição e testar os dados

In [18]:
colunas = ['data', 'lancamento', 'dcto', 'credito', 'debito', 'saldo']

df.columns = colunas
df

,data,lancamento,dcto,credito,debito,saldo
0,27/04/2026,SALDO ANTERIOR,NaN,NaN,NaN,"99.073,98"
1,28/04/2026,DEP CORBAN DINHEIRO,711128,"1.000,00",NaN,"100.073,98"
2,28/04/2026,DEP CORBAN DINHEIRO,711128,"1.000,00",NaN,"101.073,98"
3,28/04/2026,STONE MASTER DEBITO STONE INSTITUICAO DE PAGAM...,9235509,"387,09",NaN,"101.461,07"
4,28/04/2026,STONE ELO DEBITO STONE INSTITUICAO DE PAGAMENTO,9235509,"27,57",NaN,"101.488,64"
5,28/04/2026,TRANSFERENCIA PIX REM: JOAO ANDRADE DE LIMA 2...,705324,"88,00",NaN,"101.576,64"
6,28/04/2026,TRANSFERENCIA PIX REM: RENATO CORDEIRO DE SO 2...,758232,"272,00",NaN,"101.848,64"
7,28/04/2026,TRANSFERENCIA PIX REM: Francisco Antonio Per 2...,900058,"90,00",NaN,"101.938,64"
8,28/04/2026,TRANSFERENCIA PIX REM: José Ricardo Lima Roc 2...,906209,"56,00",NaN,"101.994,64"
9,28/04/2026,TRANSFERENCIA PIX REM: ALCIDES NETO QUEIROZ 2...,906476,"28,00",NaN,"102.022,64"
10,28/04/2026,TRANSFERENCIA PIX REM: Michael Duarte de Que 2...,1005501,"1.200,00",NaN,"103.222,64"
11,28/04/2026,TRANSFERENCIA PIX REM: MIGUEL RODRIGUES GURG 2...,1256370,"74,00",NaN,"103.296,64"
12,28/04/2026,TRANSFERENCIA PIX REM: CARCARA CONSTRUCOES E 2...,1404132,"62,00",NaN,"103.358,64"
13,28/04/2026,TRANSFERENCIA PIX REM: Evando da Silva Assun 2...,1503063,"266,00",NaN,"103.624,64"
14,28/04/2026,TRANSFERENCIA PIX REM: SYLVANA A SANTANA 2...,1615383,"170,00",NaN,"103.794,64"
15,28/04/2026,RENTAB.INVEST FACILCRED*,1745769,"0,44",NaN,"103.795,08"
16,28/04/2026,TARIFA REGISTRO COBRANCA QUANDO DO REGISTRO ...,9041633,NaN,"-1,99","103.793,09"
17,28/04/2026,PAGTO ELETRONICO TRIBUTO INTERNET --SEFAZ/CE,5690252,NaN,"-5.449,56","98.343,53"
18,28/04/2026,TRANSFERENCIA PIX DES: M J DINIZ & CIA LTDA 2...,1128026,NaN,"-1.500,00","96.843,53"
19,28/04/2026,TRANSFERENCIA PIX DES: S V COMERCIO DE MATER 2...,1141441,NaN,"-3.218,73","93.624,80"
20,28/04/2026,PIX QR CODE DINAMICO DES: SODINE SOCIEDADE DIS...,1511329,NaN,"-1.382,25","92.242,55"
21,29/04/2026,STONE MASTER CREDITO STONE INSTITUICAO DE PAGA...,402529,"529,25",NaN,"92.771,80"
22,29/04/2026,STONE ELO CREDITO STONE INSTITUICAO DE PAGAMENTO,402529,"516,31",NaN,"93.288,11"
23,29/04/2026,STONE MASTER DEBITO STONE INSTITUICAO DE PAGAM...,402529,"87,12",NaN,"93.375,23"
24,29/04/2026,STONE ELO DEBITO STONE INSTITUICAO DE PAGAMENTO,402529,"93,53",NaN,"93.468,76"
25,Total,NaN,NaN,"5.947,31","-11.552,53","93.468,76"
26,NaN,Lançamentos Futuros,NaN,NaN,NaN,NaN
27,Data,Lançamento,Dcto.,Crédito (R$),Débito (R$),NaN
28,30/04/2026,STONE VISA CREDITO STONE INSTITUICAO DE PAGAMENTO,159330,"169,89",NaN,NaN
29,30/04/2026,STONE MASTER CREDITO STONE INSTITUICAO DE PAGA...,159330,"353,52",NaN,NaN
30,Total do dia,NaN,NaN,"523,41","0,00",NaN
31,04/05/2026,CARTAO CREDITO ANUIDADE,4740110,NaN,"-22,00",NaN
32,Total do dia,NaN,NaN,"0,00","-22,00",NaN
33,11/05/2026,PAGTO ELETRON COBRANCA BRADESCO SEGUROS - SEG...,2425,NaN,"-916,71",NaN
34,11/05/2026,PAGTO ELETRON COBRANCA 070187494301050701BRAD...,3019,NaN,"-1.274,82",NaN
35,11/05/2026,PAGTO ELETRON COBRANCA 070187494001050902BRAD...,3020,NaN,"-582,42",NaN
36,11/05/2026,PAGTO ELETRON COBRANCA 070187493701050900BRAD...,3021,NaN,"-1.274,82",NaN
37,11/05/2026,PAGTO ELETRON COBRANCA 070187493901050902BRAD...,3022,NaN,"-1.274,82",NaN
38,11/05/2026,PAGTO ELETRON COBRANCA 070187494201050902BRAD...,3023,NaN,"-1.274,82",NaN
39,11/05/2026,PAGTO ELETRON COBRANCA 070187494401050900BRAD...,3024,NaN,"-1.274,82",NaN
40,11/05/2026,PAGTO ELETRON COBRANCA 070187493801050701BRAD...,3025,NaN,"-1.274,82",NaN
41,11/05/2026,PAGTO ELETRON COBRANCA 070187494101050902BRAD...,3026,NaN,"-1.274,82",NaN
42,Total do dia,NaN,NaN,"0,00","-10.422,87",NaN
43,NaN,Saldos Invest Fácil / Plus,NaN,NaN,NaN,NaN
44,Data,Histórico,Valor (R$),NaN,NaN,NaN
45,27/04/2026,SALDO INVEST FÁCIL,"99.077,40",NaN,NaN,NaN
46,28/04/2026,SALDO INVEST FÁCIL,"92.246,15",NaN,NaN,NaN

In [26]:
df['lancamento'] = (
    df['lancamento']
    .str.replace(r'^TRANSFERENCIA PIX REM:\s*', '', regex=True)
    .str.replace(r'\s+\d{2}/\d{2}$', '', regex=True)
    .str.strip()
)

df

,data,lancamento,dcto,credito,debito,saldo,nome
0,27/04/2026,Saldo Anterior,NaN,NaN,NaN,"99.073,98",Saldo Anterior
1,28/04/2026,Dep Corban Dinheiro,711128,"1.000,00",NaN,"100.073,98",Dep Corban Dinheiro
2,28/04/2026,Dep Corban Dinheiro,711128,"1.000,00",NaN,"101.073,98",Dep Corban Dinheiro
3,28/04/2026,Stone Master Debito Stone Instituicao De Pagam...,9235509,"387,09",NaN,"101.461,07",Stone Master Debito Stone Instituicao De Pagam...
4,28/04/2026,Stone Elo Debito Stone Instituicao De Pagamento,9235509,"27,57",NaN,"101.488,64",Stone Elo Debito Stone Instituicao De Pagamento
5,28/04/2026,Pix - Joao Andrade De Lima,705324,"88,00",NaN,"101.576,64",Pix - Joao Andrade De Lima
6,28/04/2026,Pix - Renato Cordeiro De So,758232,"272,00",NaN,"101.848,64",Pix - Renato Cordeiro De So
7,28/04/2026,Pix - Francisco Antonio Per,900058,"90,00",NaN,"101.938,64",Pix - Francisco Antonio Per
8,28/04/2026,Pix - José Ricardo Lima Roc,906209,"56,00",NaN,"101.994,64",Pix - José Ricardo Lima Roc
9,28/04/2026,Pix - Alcides Neto Queiroz,906476,"28,00",NaN,"102.022,64",Pix - Alcides Neto Queiroz
10,28/04/2026,Pix - Michael Duarte De Que,1005501,"1.200,00",NaN,"103.222,64",Pix - Michael Duarte De Que
11,28/04/2026,Pix - Miguel Rodrigues Gurg,1256370,"74,00",NaN,"103.296,64",Pix - Miguel Rodrigues Gurg
12,28/04/2026,Pix - Carcara Construcoes E,1404132,"62,00",NaN,"103.358,64",Pix - Carcara Construcoes E
13,28/04/2026,Pix - Evando Da Silva Assun,1503063,"266,00",NaN,"103.624,64",Pix - Evando Da Silva Assun
14,28/04/2026,Pix - Sylvana A Santana,1615383,"170,00",NaN,"103.794,64",Pix - Sylvana A Santana
15,28/04/2026,Rentab.Invest Facilcred*,1745769,"0,44",NaN,"103.795,08",Rentab.Invest Facilcred*
16,28/04/2026,Tarifa Registro Cobranca Quando Do Registro ...,9041633,NaN,"-1,99","103.793,09",Tarifa Registro Cobranca Quando Do Registro ...
17,28/04/2026,Pagto Eletronico Tributo Internet --Sefaz/Ce,5690252,NaN,"-5.449,56","98.343,53",Pagto Eletronico Tributo Internet --Sefaz/Ce
18,28/04/2026,Transferencia Pix Des: M J Diniz & Cia Ltda,1128026,NaN,"-1.500,00","96.843,53",Transferencia Pix Des: M J Diniz & Cia Ltda
19,28/04/2026,Transferencia Pix Des: S V Comercio De Mater,1141441,NaN,"-3.218,73","93.624,80",Transferencia Pix Des: S V Comercio De Mater
20,28/04/2026,Pix Qr Code Dinamico Des: Sodine Sociedade Dist,1511329,NaN,"-1.382,25","92.242,55",Pix Qr Code Dinamico Des: Sodine Sociedade Dist
21,29/04/2026,Stone Master Credito Stone Instituicao De Paga...,402529,"529,25",NaN,"92.771,80",Stone Master Credito Stone Instituicao De Paga...
22,29/04/2026,Stone Elo Credito Stone Instituicao De Pagamento,402529,"516,31",NaN,"93.288,11",Stone Elo Credito Stone Instituicao De Pagamento
23,29/04/2026,Stone Master Debito Stone Instituicao De Pagam...,402529,"87,12",NaN,"93.375,23",Stone Master Debito Stone Instituicao De Pagam...
24,29/04/2026,Stone Elo Debito Stone Instituicao De Pagamento,402529,"93,53",NaN,"93.468,76",Stone Elo Debito Stone Instituicao De Pagamento
25,Total,NaN,NaN,"5.947,31","-11.552,53","93.468,76",NaN
26,NaN,Lançamentos Futuros,NaN,NaN,NaN,NaN,Lançamentos Futuros
27,Data,Lançamento,Dcto.,Crédito (R$),Débito (R$),NaN,Lançamento
28,30/04/2026,Stone Visa Credito Stone Instituicao De Pagamento,159330,"169,89",NaN,NaN,Stone Visa Credito Stone Instituicao De Pagamento
29,30/04/2026,Stone Master Credito Stone Instituicao De Paga...,159330,"353,52",NaN,NaN,Stone Master Credito Stone Instituicao De Paga...
30,Total do dia,NaN,NaN,"523,41","0,00",NaN,NaN
31,04/05/2026,Cartao Credito Anuidade,4740110,NaN,"-22,00",NaN,Cartao Credito Anuidade
32,Total do dia,NaN,NaN,"0,00","-22,00",NaN,NaN
33,11/05/2026,Pagto Eletron Cobranca Bradesco Seguros - Seg...,2425,NaN,"-916,71",NaN,Pagto Eletron Cobranca Bradesco Seguros - Seg...
34,11/05/2026,Pagto Eletron Cobranca 070187494301050701Brad...,3019,NaN,"-1.274,82",NaN,Pagto Eletron Cobranca 070187494301050701Brad...
35,11/05/2026,Pagto Eletron Cobranca 070187494001050902Brad...,3020,NaN,"-582,42",NaN,Pagto Eletron Cobranca 070187494001050902Brad...
36,11/05/2026,Pagto Eletron Cobranca 070187493701050900Brad...,3021,NaN,"-1.274,82",NaN,Pagto Eletron Cobranca 070187493701050900Brad...
37,11/05/2026,Pagto Eletron Cobranca 070187493901050902Brad...,3022,NaN,"-1.274,82",NaN,Pagto Eletron Cobranca 070187493901050902Brad...
38,11/05/2026,Pagto Eletron Cobranca 070187494201050902Brad...,3023,NaN,"-1.274,82",NaN,Pagto Eletron Cobranca 070187494201050902Brad...
39,11/05/2026,Pagto Eletron Cobranca 070187494401050900Brad...,3024,NaN,"-1.274,82",NaN,Pagto Eletron Cobranca 070187494401050900Brad...
40,11/05/2026,Pagto Eletron Cobranca 070187493801050701Brad...,3025,NaN,"-1.274,82",NaN,Pagto Eletron Cobranca 070187493801050701Brad...
41,11/05/2026,Pagto Eletron Cobranca 070187494101050902Brad...,3026,NaN,"-1.274,82",NaN,Pagto Eletron Cobranca 070187494101050902Brad...
42,Total do dia,NaN,NaN,"0,00","-10.422,87",NaN,NaN
43,NaN,Saldos Invest Fácil / Plus,NaN,NaN,NaN,NaN,Saldos Invest Fácil / Plus
44,Data,Histórico,Valor (R$),NaN,NaN,NaN,Histórico
45,27/04/2026,Saldo Invest Fácil,"99.077,40",NaN,NaN,NaN,Saldo Invest Fácil
46,28/04/2026,Saldo Invest Fácil,"92.246,15",NaN,NaN,NaN,Saldo Invest Fácil