Importação e visualização inicial do extrato bancário

In [3]:
import pandas as pd
from pathlib import Path

BASE_DIR = Path.cwd().parent
DATA_DIR = BASE_DIR / "data"
RAW_DIR = DATA_DIR / 'raw'
RAW_FILE = RAW_DIR / "extrato.csv"

df = pd.read_csv(
    RAW_FILE,
    sep=';',
    skiprows=2,
    encoding='latin1'
)

df

,05/05/2026,SALDO ANTERIOR,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,06/05/2026,TRANSFERENCIA PIX REM: ALEX PEREIRA POATAN 06/05,6166116,110,NaN
1,06/05/2026,TRANSFERENCIA PIX REM: ANDERSON SILVA SPIDER 0...,1234162,158,NaN
2,06/05/2026,TRANSFERENCIA PIX REM: MATHEUS BRASILEIRO 06/05,6214234213,285,NaN
3,06/05/2026,TRANSFERENCIA PIX REM: ANITA SILVA 06/05,5123512,42,NaN
4,06/05/2026,TRANSFERENCIA PIX REM: LUIS INACIO 06/05,151161616,180,NaN
5,06/05/2026,TRANSFERENCIA PIX REM: TRUMP DA SILVA SANTOS 0...,34153216512,90,NaN
6,06/05/2026,TRANSFERENCIA PIX REM: MERCADINHO ALEGRIA 06/05,1446049,213,NaN
7,06/05/2026,TRANSFERENCIA PIX REM: TOYOTA COROLA 06/05,1447224,566,NaN
8,06/05/2026,TRANSFERENCIA PIX REM: MERCADO PAGO 06/05,1541274,83,NaN
9,06/05/2026,TRANSFERENCIA PIX REM: FORRO DE QUALIDADE 06/05,52112125,90,NaN
10,06/05/2026,TRANSFERENCIA PIX REM: Pedro Alvares Cabral 06/05,511155151,85,NaN
11,06/05/2026,TRANSFERENCIA PIX REM: Dona Leupodina 06/05,5112521521,54,NaN
12,06/05/2026,RENTAB.INVEST FACILCRED*,34214423,"0,08",NaN
13,06/05/2026,RENTAB.INVEST FACILCRED*,15412515,"0,01",NaN
14,06/05/2026,PAGTO ELETRON COBRANCA PAGAMENTO MERCANTE E ROFE,1525132,NaN,"-9.889,90"
15,06/05/2026,PAGTO ELETRONICO TRIBUTO INTERNET --SEFAZ/CE,513251215,NaN,"-220,45"
16,06/05/2026,PAGTO ELETRONICO TRIBUTO INTERNET --SEFAZ/CE,1412321,NaN,"-220,45"
17,06/05/2026,PAGTO ELETRONICO TRIBUTO INTERNET --SEFAZ/CE,4114211,NaN,"-359,3"
18,06/05/2026,TARIFA TRANSFEREN VALOR TAR TRANSF VR,311131,NaN,"-18,6"
19,07/05/2026,LIQUIDACAO DE COBRANCA VALOR DISPONIVEL,13313113,"11.940,10",NaN
20,07/05/2026,TRANSFERENCIA PIX REM: WELVIS PRESLEY 07/05,15151253,96,NaN
21,07/05/2026,TRANSFERENCIA PIX REM: AVENIDA CASTELO BRANCO ...,314142,168,NaN
22,07/05/2026,TRANSFERENCIA PIX REM: Pedro Alvares CABRAL 07/05,32121551,143,NaN
23,07/05/2026,TRANSFERENCIA PIX REM: Luis Inacio de Brasilia...,4511616,183,NaN
24,07/05/2026,TRANSFERENCIA PIX REM: Play Store 07/05,61614124,88,NaN
25,07/05/2026,TRANSFERENCIA PIX REM: God Of War 07/05,651214,358,NaN
26,07/05/2026,TRANSFERENCIA PIX REM: CANETA AZUL 07/05,657659,257,NaN
27,07/05/2026,TRANSFERENCIA PIX REM: TIRINGA HUMORISTA 07/05,9505865645,102,NaN
28,07/05/2026,TRANSFERENCIA PIX REM: Pagina da Choquei 07/05,865654543,153,NaN
29,07/05/2026,TRANSFERENCIA PIX REM: MC RYAN SP 07/05,3215451,372,NaN
30,07/05/2026,TRANSFERENCIA PIX REM: Mercado Pago 07/05,252523,836,NaN
31,07/05/2026,TRANSFERENCIA PIX REM: Organização Python 07/05,2352661,55,NaN
32,07/05/2026,DEP DINHEIRO BCO 24H,403972,"1.800,00",NaN
33,07/05/2026,DEP DINHEIRO BCO 24H,403974,"1.700,00",NaN
34,Total,NaN,NaN,"26.353,84","-10.708,70"
35,NaN,NaN,NaN,NaN,NaN
36,NaN,Lançamentos Futuros,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN
38,Data,Lançamento,Dcto.,Crédito (R$),Débito (R$)
39,08/05/2026,LIQUIDACAO DE COBRANCA VALOR DISPONIVEL,5165500,"8.400,00",NaN
40,08/05/2026,STONE MASTER CREDITO STONE INSTITUICAO DE PAGA...,106510,"507,69",NaN
41,Total do dia,NaN,NaN,"8.907,69",0
42,11/05/2026,PAGTO ELETRON COBRANCA BRADESCO SEGUROS - SEG...,605110,NaN,"-916,71"
43,11/05/2026,PAGTO ELETRON COBRANCA 070187494301050701BRAD...,150610,NaN,"-1.274,82"
44,11/05/2026,PAGTO ELETRON COBRANCA 070187494001050902BRAD...,150510,NaN,"-582,42"
45,11/05/2026,PAGTO ELETRON COBRANCA 070187493701050900BRAD...,15610,NaN,"-1.274,82"
46,11/05/2026,PAGTO ELETRON COBRANCA 070187493901050902BRAD...,1051605,NaN,"-1.274,82"
47,11/05/2026,PAGTO ELETRON COBRANCA 070187494201050902BRAD...,150165,NaN,"-1.274,82"
48,11/05/2026,PAGTO ELETRON COBRANCA 070187494401050900BRAD...,510616,NaN,"-1.274,82"
49,11/05/2026,PAGTO ELETRON COBRANCA 070187493801050701BRAD...,160565,NaN,"-1.274,82"
50,11/05/2026,PAGTO ELETRON COBRANCA 070187494101050902BRAD...,160778,NaN,"-1.274,82"
51,Total do dia,NaN,NaN,0,"-10.422,87"
52,NaN,Saldos Invest Fácil / Plus,NaN,NaN,NaN
53,NaN,NaN,NaN,NaN,NaN
54,Data,Histórico,Valor (R$),NaN,NaN
55,05/05/2026,SALDO INVEST FÁCIL,"0,00",NaN,NaN
56,06/05/2026,SALDO INVEST FÁCIL,"0,00",NaN,NaN

Vou fazer uma pré limpeza, só pra exibição e testar os dados

In [5]:
colunas = ['data', 'lancamento', 'dcto', 'credito', 'debito']

df.columns = colunas
df

,data,lancamento,dcto,credito,debito
0,06/05/2026,TRANSFERENCIA PIX REM: ALEX PEREIRA POATAN 06/05,6166116,110,NaN
1,06/05/2026,TRANSFERENCIA PIX REM: ANDERSON SILVA SPIDER 0...,1234162,158,NaN
2,06/05/2026,TRANSFERENCIA PIX REM: MATHEUS BRASILEIRO 06/05,6214234213,285,NaN
3,06/05/2026,TRANSFERENCIA PIX REM: ANITA SILVA 06/05,5123512,42,NaN
4,06/05/2026,TRANSFERENCIA PIX REM: LUIS INACIO 06/05,151161616,180,NaN
5,06/05/2026,TRANSFERENCIA PIX REM: TRUMP DA SILVA SANTOS 0...,34153216512,90,NaN
6,06/05/2026,TRANSFERENCIA PIX REM: MERCADINHO ALEGRIA 06/05,1446049,213,NaN
7,06/05/2026,TRANSFERENCIA PIX REM: TOYOTA COROLA 06/05,1447224,566,NaN
8,06/05/2026,TRANSFERENCIA PIX REM: MERCADO PAGO 06/05,1541274,83,NaN
9,06/05/2026,TRANSFERENCIA PIX REM: FORRO DE QUALIDADE 06/05,52112125,90,NaN
10,06/05/2026,TRANSFERENCIA PIX REM: Pedro Alvares Cabral 06/05,511155151,85,NaN
11,06/05/2026,TRANSFERENCIA PIX REM: Dona Leupodina 06/05,5112521521,54,NaN
12,06/05/2026,RENTAB.INVEST FACILCRED*,34214423,"0,08",NaN
13,06/05/2026,RENTAB.INVEST FACILCRED*,15412515,"0,01",NaN
14,06/05/2026,PAGTO ELETRON COBRANCA PAGAMENTO MERCANTE E ROFE,1525132,NaN,"-9.889,90"
15,06/05/2026,PAGTO ELETRONICO TRIBUTO INTERNET --SEFAZ/CE,513251215,NaN,"-220,45"
16,06/05/2026,PAGTO ELETRONICO TRIBUTO INTERNET --SEFAZ/CE,1412321,NaN,"-220,45"
17,06/05/2026,PAGTO ELETRONICO TRIBUTO INTERNET --SEFAZ/CE,4114211,NaN,"-359,3"
18,06/05/2026,TARIFA TRANSFEREN VALOR TAR TRANSF VR,311131,NaN,"-18,6"
19,07/05/2026,LIQUIDACAO DE COBRANCA VALOR DISPONIVEL,13313113,"11.940,10",NaN
20,07/05/2026,TRANSFERENCIA PIX REM: WELVIS PRESLEY 07/05,15151253,96,NaN
21,07/05/2026,TRANSFERENCIA PIX REM: AVENIDA CASTELO BRANCO ...,314142,168,NaN
22,07/05/2026,TRANSFERENCIA PIX REM: Pedro Alvares CABRAL 07/05,32121551,143,NaN
23,07/05/2026,TRANSFERENCIA PIX REM: Luis Inacio de Brasilia...,4511616,183,NaN
24,07/05/2026,TRANSFERENCIA PIX REM: Play Store 07/05,61614124,88,NaN
25,07/05/2026,TRANSFERENCIA PIX REM: God Of War 07/05,651214,358,NaN
26,07/05/2026,TRANSFERENCIA PIX REM: CANETA AZUL 07/05,657659,257,NaN
27,07/05/2026,TRANSFERENCIA PIX REM: TIRINGA HUMORISTA 07/05,9505865645,102,NaN
28,07/05/2026,TRANSFERENCIA PIX REM: Pagina da Choquei 07/05,865654543,153,NaN
29,07/05/2026,TRANSFERENCIA PIX REM: MC RYAN SP 07/05,3215451,372,NaN
30,07/05/2026,TRANSFERENCIA PIX REM: Mercado Pago 07/05,252523,836,NaN
31,07/05/2026,TRANSFERENCIA PIX REM: Organização Python 07/05,2352661,55,NaN
32,07/05/2026,DEP DINHEIRO BCO 24H,403972,"1.800,00",NaN
33,07/05/2026,DEP DINHEIRO BCO 24H,403974,"1.700,00",NaN
34,Total,NaN,NaN,"26.353,84","-10.708,70"
35,NaN,NaN,NaN,NaN,NaN
36,NaN,Lançamentos Futuros,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN
38,Data,Lançamento,Dcto.,Crédito (R$),Débito (R$)
39,08/05/2026,LIQUIDACAO DE COBRANCA VALOR DISPONIVEL,5165500,"8.400,00",NaN
40,08/05/2026,STONE MASTER CREDITO STONE INSTITUICAO DE PAGA...,106510,"507,69",NaN
41,Total do dia,NaN,NaN,"8.907,69",0
42,11/05/2026,PAGTO ELETRON COBRANCA BRADESCO SEGUROS - SEG...,605110,NaN,"-916,71"
43,11/05/2026,PAGTO ELETRON COBRANCA 070187494301050701BRAD...,150610,NaN,"-1.274,82"
44,11/05/2026,PAGTO ELETRON COBRANCA 070187494001050902BRAD...,150510,NaN,"-582,42"
45,11/05/2026,PAGTO ELETRON COBRANCA 070187493701050900BRAD...,15610,NaN,"-1.274,82"
46,11/05/2026,PAGTO ELETRON COBRANCA 070187493901050902BRAD...,1051605,NaN,"-1.274,82"
47,11/05/2026,PAGTO ELETRON COBRANCA 070187494201050902BRAD...,150165,NaN,"-1.274,82"
48,11/05/2026,PAGTO ELETRON COBRANCA 070187494401050900BRAD...,510616,NaN,"-1.274,82"
49,11/05/2026,PAGTO ELETRON COBRANCA 070187493801050701BRAD...,160565,NaN,"-1.274,82"
50,11/05/2026,PAGTO ELETRON COBRANCA 070187494101050902BRAD...,160778,NaN,"-1.274,82"
51,Total do dia,NaN,NaN,0,"-10.422,87"
52,NaN,Saldos Invest Fácil / Plus,NaN,NaN,NaN
53,NaN,NaN,NaN,NaN,NaN
54,Data,Histórico,Valor (R$),NaN,NaN
55,05/05/2026,SALDO INVEST FÁCIL,"0,00",NaN,NaN
56,06/05/2026,SALDO INVEST FÁCIL,"0,00",NaN,NaN

In [6]:
df['lancamento'] = (
    df['lancamento']
    .str.replace(r'^TRANSFERENCIA PIX REM:\s*', '', regex=True)
    .str.replace(r'\s+\d{2}/\d{2}$', '', regex=True)
    .str.strip()
)

df

,data,lancamento,dcto,credito,debito
0,06/05/2026,ALEX PEREIRA POATAN,6166116,110,NaN
1,06/05/2026,ANDERSON SILVA SPIDER,1234162,158,NaN
2,06/05/2026,MATHEUS BRASILEIRO,6214234213,285,NaN
3,06/05/2026,ANITA SILVA,5123512,42,NaN
4,06/05/2026,LUIS INACIO,151161616,180,NaN
5,06/05/2026,TRUMP DA SILVA SANTOS,34153216512,90,NaN
6,06/05/2026,MERCADINHO ALEGRIA,1446049,213,NaN
7,06/05/2026,TOYOTA COROLA,1447224,566,NaN
8,06/05/2026,MERCADO PAGO,1541274,83,NaN
9,06/05/2026,FORRO DE QUALIDADE,52112125,90,NaN
10,06/05/2026,Pedro Alvares Cabral,511155151,85,NaN
11,06/05/2026,Dona Leupodina,5112521521,54,NaN
12,06/05/2026,RENTAB.INVEST FACILCRED*,34214423,"0,08",NaN
13,06/05/2026,RENTAB.INVEST FACILCRED*,15412515,"0,01",NaN
14,06/05/2026,PAGTO ELETRON COBRANCA PAGAMENTO MERCANTE E ROFE,1525132,NaN,"-9.889,90"
15,06/05/2026,PAGTO ELETRONICO TRIBUTO INTERNET --SEFAZ/CE,513251215,NaN,"-220,45"
16,06/05/2026,PAGTO ELETRONICO TRIBUTO INTERNET --SEFAZ/CE,1412321,NaN,"-220,45"
17,06/05/2026,PAGTO ELETRONICO TRIBUTO INTERNET --SEFAZ/CE,4114211,NaN,"-359,3"
18,06/05/2026,TARIFA TRANSFEREN VALOR TAR TRANSF VR,311131,NaN,"-18,6"
19,07/05/2026,LIQUIDACAO DE COBRANCA VALOR DISPONIVEL,13313113,"11.940,10",NaN
20,07/05/2026,WELVIS PRESLEY,15151253,96,NaN
21,07/05/2026,AVENIDA CASTELO BRANCO,314142,168,NaN
22,07/05/2026,Pedro Alvares CABRAL,32121551,143,NaN
23,07/05/2026,Luis Inacio de Brasilia,4511616,183,NaN
24,07/05/2026,Play Store,61614124,88,NaN
25,07/05/2026,God Of War,651214,358,NaN
26,07/05/2026,CANETA AZUL,657659,257,NaN
27,07/05/2026,TIRINGA HUMORISTA,9505865645,102,NaN
28,07/05/2026,Pagina da Choquei,865654543,153,NaN
29,07/05/2026,MC RYAN SP,3215451,372,NaN
30,07/05/2026,Mercado Pago,252523,836,NaN
31,07/05/2026,Organização Python,2352661,55,NaN
32,07/05/2026,DEP DINHEIRO BCO 24H,403972,"1.800,00",NaN
33,07/05/2026,DEP DINHEIRO BCO 24H,403974,"1.700,00",NaN
34,Total,NaN,NaN,"26.353,84","-10.708,70"
35,NaN,NaN,NaN,NaN,NaN
36,NaN,Lançamentos Futuros,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN
38,Data,Lançamento,Dcto.,Crédito (R$),Débito (R$)
39,08/05/2026,LIQUIDACAO DE COBRANCA VALOR DISPONIVEL,5165500,"8.400,00",NaN
40,08/05/2026,STONE MASTER CREDITO STONE INSTITUICAO DE PAGA...,106510,"507,69",NaN
41,Total do dia,NaN,NaN,"8.907,69",0
42,11/05/2026,PAGTO ELETRON COBRANCA BRADESCO SEGUROS - SEG...,605110,NaN,"-916,71"
43,11/05/2026,PAGTO ELETRON COBRANCA 070187494301050701BRAD...,150610,NaN,"-1.274,82"
44,11/05/2026,PAGTO ELETRON COBRANCA 070187494001050902BRAD...,150510,NaN,"-582,42"
45,11/05/2026,PAGTO ELETRON COBRANCA 070187493701050900BRAD...,15610,NaN,"-1.274,82"
46,11/05/2026,PAGTO ELETRON COBRANCA 070187493901050902BRAD...,1051605,NaN,"-1.274,82"
47,11/05/2026,PAGTO ELETRON COBRANCA 070187494201050902BRAD...,150165,NaN,"-1.274,82"
48,11/05/2026,PAGTO ELETRON COBRANCA 070187494401050900BRAD...,510616,NaN,"-1.274,82"
49,11/05/2026,PAGTO ELETRON COBRANCA 070187493801050701BRAD...,160565,NaN,"-1.274,82"
50,11/05/2026,PAGTO ELETRON COBRANCA 070187494101050902BRAD...,160778,NaN,"-1.274,82"
51,Total do dia,NaN,NaN,0,"-10.422,87"
52,NaN,Saldos Invest Fácil / Plus,NaN,NaN,NaN
53,NaN,NaN,NaN,NaN,NaN
54,Data,Histórico,Valor (R$),NaN,NaN
55,05/05/2026,SALDO INVEST FÁCIL,"0,00",NaN,NaN
56,06/05/2026,SALDO INVEST FÁCIL,"0,00",NaN,NaN